### ISSUE TITLE
Various QOL improvements

### ISSUE THREAD

**Issue by Kirillathome** [Kirillathome/FNAK-Feedback#8]
I plan to add a lot of quality of life improvements to Alpha 2. Such as:

- [ ] randomized animatronic spawn locations, so you can't just camp one spot
- [ ] change UI a bit #4 (make stuff better, e.g. custom textures for camera buttons)
- [ ] allow switching between items (e.g. flashlight <-> camera) to support #6 
- [ ] improve Nirill AI to make it actually a threat
- [ ] ambient sounds (maybe)
- [ ] do some balancing #3 
- [ ] fix many hidden bugs <sup>nobody would never notice</sup>

I will probably expand this list, as I plan to make Alpha 2 a big update. I will also take suggestions from the comments (so basically only from @Zenitsuy)

**Comment by Kirillathome** [comment]
You can now switch between using the flashlight and using the camera.
The item in use is highlighted in the HUD.

![hud](https://github.com/Kirillathome/FNAK-Feedback/assets/99025071/bc8e7d84-23e6-4079-b347-f9d2699d4b9e)

**Comment by Kirillathome** [comment]
Added a **beep** sound when pressing buttons, also added two new options: ``master_volume`` and ``sfx_volume``.
